name: Unzip File

on:
  workflow_dispatch: # Allows you to manually trigger this workflow
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Unzip the file
      - name: Unzip the volcano-mobile-pwa.zip file
        run: |
          unzip volcano-mobile-pwa.zip -d extracted_files
          ls extracted_files

      # Step 3: Commit and push extracted files back to the repository
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add extracted_files
          git commit -m "Unzipped volcano-mobile-pwa.zip"
          git push
